name: Release

on:
  push:
    branches: main

permissions:
    contents: write
    issues: write
    pull-requests: write

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
          cache: npm
          cache-dependency-path: |
            package-lock.json
            examples/express/package-lock.json

      - run: npm ci
        working-directory: .

      - run: |
          echo "\`\`\`" > report.md
          npm run start:bun | tail -n +4 | tee -a report.md
          echo "\`\`\`" >> report.md
        working-directory: .
          
      # - name: "🏷️ Push tag"
      #   uses: EndBug/latest-tag@latest
      #   with:
      #     force-branch: true

      - uses: ncipollo/release-action@98d25d4189e9b6cee19b8635b1ea5cc39c158a41
        with:
          tag: v0-${{ github.sha }}
          artifacts: "report.md"
          bodyFile: "report.md"
